---

- name: Delete nat gateway and wait for deleted status.
  ec2_vpc_nat_gateway:
    nat_gateway_id: "{{ nat_id }}" 
    wait: yes
    wait_timeout: 500
    region: "{{ region_name }}"
    state: absent
