---
- name: Get details on specific nat gateways
  ec2_vpc_nat_gateway_facts:
    nat_gateway_ids:
      - "{{ vnatgw_id }}"
    region: us-west-2
  register: specific_ngws

#- name: Delete Elastic IP
 # ec2_eip:
  #  ip: "{{ elastic_ip }}"
   # region: "{{ region_name }}"
    #state: absent
