---
# tasks file for roles/ansiblepull

    - name: Create local directory to work from
      file: path={{workdir}} state=directory owner=ec2-user group=ec2-user mode=0751

    - name: Copy ansible inventory file to client
      copy: src=/etc/ansible/hosts dest=/etc/ansible/hosts owner=ec2-user group=ec2-user mode=0644

    - name: Create crontab entry to clone/pull git repository
      template: src=ansible-pull.j2 dest=/etc/cron.d/ansible-pull owner=ec2-user group=ec2-user mode=0644

    - name: Create logrotate entry for ansible-pull.log
      template: src=logrotate_ansible-pull.j2 dest=/etc/logrotate.d/ansible-pull owner=ec2-user group=ec2-user mode=0644
