---
# Install Java for (RedHat)
- name: Install Java 1.7
  yum: name=java-1.7.0-openjdk state=present

- name: add group "tomcatuser"
  group: name=tomcatuser

- name: add user "tomcatuser"
  user: name=tomcatuser group=tomcatuser home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo


# Installing Packages
- name: Install Tomcat7 (Ubuntu)
  apt: pkg={{ item }} state=latest
  with_items:
    - tomcat7
    - libtcnative-1
    - libapr1
  when: ansible_distribution == 'Ubuntu'

- name: Install Tomcat7 (Debian)
  apt: pkg={{ item }} state=latest
  with_items:
    - tomcat7
  when: ansible_distribution == 'Debian'

- name: Install Tomcat7 (Amazon Linux)
  yum: pkg={{ item }} state=latest
  with_items:
    - tomcat
  when: ansible_distribution == 'RedHat'

# Creating Tomcat Symlinks
- name: Symlink to /usr/local/tomcat
  file: dest=/usr/local/tomcat state=link src=/var/lib/tomcat7
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Symlink to /usr/local/tomcat
  file: dest=/usr/local/tomcat state=link src=/usr/share/tomcat
  when: ansible_distribution == 'RedHat'

# Setting Deploy Directory File Permissions
- name: Set Tomcat Deployment Directory Permissions
  file: dest=/usr/local/tomcat/webapps state=directory owner={{ tomcat_user }}  group={{ tomcat_user }}  mode=0775
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

# Creating Service Configuration
- name: Configuring Tomcat Service (Ubuntu / Debian)
  template: src=tomcat7.j2 dest=/etc/default/tomcat7 owner=root group=root mode=0644
  notify: restart_tomcat
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Configuring Tomcat Service (Amazon)
  template: src=tomcat.conf.j2 dest=/etc/tomcat/tomcat.conf owner={{ tomcat_user }}  group={{ tomcat_user }}  mode=644
  notify: restart_tomcat
  when: ansible_distribution == 'RedHat'

- name: Enable Tomcat Service
  service: name=tomcat enabled=yes
