---
- name: Ensure required packages and installed and up to date
  yum: pkg={{ item }} state=present
  with_items:
     - make
     - gcc
     - perl
     - wget
     - unzip
     - tar

- name: JAVA| check if java is already installed
  stat: path=/opt/jdk-8u112-linux-x64.tar.gz
  register: Java_binary
- block:
  - name: Java| Download Javaa
    get_url:
      url: "{{JAVA_REPO}}"
      dest: "{{JAVA_HOME}}"
  - name: Java| explode Java tar
    unarchive:
      copy: no
      src: "{{JAVA_HOME}}{{JAVA_SOURCE}}"
      dest: "{{JAVA_HOME}}" 
  - name: Java| check for profile.d file
    stat: path=~/.bashrc
    register: bashrc  
  - name: Java| add java home
    lineinfile:
      dest: ~/.bashrc
      line: export JAVA_HOME={{JAVA_HOME}}{{JAVA_VERSION}}
      state: present
    when: bashrc.stat.exists  
  when: not Java_binary.stat.exists       
