---
#File roles/ec2/tasks/main.yml

 - name: assign inventory
   template: src='hosts.yml' dest='/home/ec2-user/ejdemo/hosts.yml'

 - name: Initiate test and development compute environment provisioning for "{{ Venvironment }}"
   include: tnd.yml
   static: no
   when: Vstage is defined and Vstage == "TND"

 - name: Initiate Pre-Production compute environment provisioning for "{{ Venvironment }}"
   include: ppd.yml
   static: no
   when: Vstage is defined and Vstage == "PPD"

 - name: Initiate Production compute environment provisioning for "{{ Venvironment }}"
   include: prd.yml
   static: no
   when: Vstage is defined and Vstage == "PRD"

